### ISSUE TITLE
Won't compile with new znc 1.6

### ISSUE THREAD

**Issue by Jusix** [jreese/znc-push#141]
Building "push.so" for ZNC 1.6.0... In file included from /usr/include/znc/Socket.h:21:0,
                 from /usr/include/znc/Client.h:21,
                 from /usr/include/znc/znc.h:21,
                 from push.cpp:14:
/usr/include/znc/Csocket.h:83:27: fatal error: unicode/ucnv.h: Datei oder Verzeichnis nicht gefunden
 # include <unicode/ucnv.h>
                           ^
compilation terminated.
[ !! ] Error while building "push.so"

**Comment by Mikaela** [comment]
You might want to try the  [python branch](https://github.com/jreese/znc-push/tree/python) which is going to replace the current cpp anyway.

**Comment by Jusix** [comment]
Thank you very much! The python version works.

**Comment by dgw** [comment]
I was able to build the C++ version—but as long as @Jusix got it working all's good, right?

**Comment by jreese** [comment]
FWIW, the master branch (c++ version) builds correctly for me with a fresh build of znc's 1.6.0 git tag.  You should ensure that if you're building from git that you update all submodules appropriately --`git submodule update --init --recursive` should be good -- and then do `make distclean` and then rerun bootstrap/configure/make.
