### ISSUE TITLE
Fails to build on Ubuntu 12.04 LTS with znc/IRCNetwork.h: No such file or directory

### ISSUE THREAD

**Issue by mgedmin** [jreese/znc-push#76]
The README claims support for ZNC versions as old as 0.078.  Ubuntu 12.04 LTS comes with znc 0.206.  When I try to build there, I get the following error:

```
$ sudo apt-get install znc-dev libcurl4-openssl-dev
$ make curl=yes
sed -i -e "s|PUSHVERSION \".*\"|PUSHVERSION \"v1.0.0-46-g20d3f02-dirty\"|" push.cpp
CXXFLAGS=" -DUSE_CURL -lcurl" LIBS=" -DUSE_CURL -lcurl" znc-buildmod push.cpp
Building "push.so" for znc 0.206... push.cpp:17:28: fatal error: znc/IRCNetwork.h: No such file or directory
compilation terminated.
[ !! ] Error while building "push.so"
make: *** [push.so] Error 1
```

Looks like https://github.com/jreese/znc-push/commit/6c413a91e688c2fe4d7a66fc70a80614b71696ac broke compatibility with older znc versions.
