### ISSUE TITLE
Doesn't build on ZNC 1.6.3?

### ISSUE THREAD

**Issue by Daniel15** [jreese/znc-push#204]
I'm getting these errors:
```
CXXFLAGS=" -DPUSHVERSION=\"v1.0.0-136-gd5908dc\" -DUSE_CURL -lcurl" LIBS=" -DUSE_CURL -lcurl" \
         znc-buildmod push.cpp
Building "push.so" for ZNC 1.6.3... In file included from /usr/include/znc/ZNCDebug.h:21:0,
                 from /usr/include/znc/defines.h:24,
                 from /usr/include/znc/Csocket.h:43,
                 from /usr/include/znc/Socket.h:21,
                 from /usr/include/znc/Client.h:21,
                 from /usr/include/znc/znc.h:21,
                 from push.cpp:16:
/usr/include/znc/ZNCString.h:85:47: error: ‘CaseSensitivity’ is not a class or namespace
  static const CaseSensitivity CaseSensitive = CaseSensitivity::CaseSensitive;
                                               ^
/usr/include/znc/ZNCString.h:86:49: error: ‘CaseSensitivity’ is not a class or namespace
  static const CaseSensitivity CaseInsensitive = CaseSensitivity::CaseInsensitive;
                                                 ^
In file included from /usr/include/znc/znc.h:21:0,
                 from push.cpp:16:
/usr/include/znc/Client.h:191:7: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  std::shared_ptr<CAuthBase> m_spAuth;
       ^
In file included from /usr/include/znc/WebModules.h:21:0,
                 from /usr/include/znc/Modules.h:21,
                 from /usr/include/znc/znc.h:22,
                 from push.cpp:16:
/usr/include/znc/Template.h:128:23: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  CTemplate(const std::shared_ptr<CTemplateOptions>& Options, CTemplate* pParent = NULL) : MCString(), m_spOptions(Options
                       ^
/usr/include/znc/Template.h:128:33: error: expected ‘,’ or ‘...’ before ‘<’ token
  CTemplate(const std::shared_ptr<CTemplateOptions>& Options, CTemplate* pParent = NULL) : MCString(), m_spOptions(Options
                                 ^
/usr/include/znc/Template.h:136:26: error: ‘std::shared_ptr’ has not been declared
  void AddTagHandler(std::shared_ptr<CTemplateTagHandler> spTagHandler) {
                          ^
/usr/include/znc/Template.h:136:36: error: expected ‘,’ or ‘...’ before ‘<’ token
  void AddTagHandler(std::shared_ptr<CTemplateTagHandler> spTagHandler) {
                                    ^
/usr/include/znc/Template.h:140:14: error: ‘shared_ptr’ is not a member of ‘std’
  std::vector<std::shared_ptr<CTemplateTagHandler> >& GetTagHandlers() {
              ^
/usr/include/znc/Template.h:140:14: error: ‘shared_ptr’ is not a member of ‘std’
/usr/include/znc/Template.h:140:49: error: template argument 1 is invalid
  std::vector<std::shared_ptr<CTemplateTagHandler> >& GetTagHandlers() {
                                                 ^
/usr/include/znc/Template.h:140:49: error: template argument 2 is invalid
/usr/include/znc/Template.h:140:51: error: expected unqualified-id before ‘>’ token
  std::vector<std::shared_ptr<CTemplateTagHandler> >& GetTagHandlers() {
                                                   ^
In file included from /usr/include/znc/znc.h:22:0,
                 from push.cpp:16:
push.cpp:2010:1: error: expected ‘}’ at end of input
 NETWORKMODULEDEFS(CPushMod, "Send highlights and personal messages to a push notification service")
 ^
In file included from /usr/include/znc/WebModules.h:21:0,
                 from /usr/include/znc/Modules.h:21,
                 from /usr/include/znc/znc.h:22,
                 from push.cpp:16:
/usr/include/znc/Template.h: In constructor ‘CTemplate::CTemplate()’:
/usr/include/znc/Template.h:120:28: error: class ‘CTemplate’ does not have any field named ‘m_spOptions’
  CTemplate() : MCString(), m_spOptions(new CTemplateOptions) {
                            ^
/usr/include/znc/Template.h:121:8: error: ‘Init’ was not declared in this scope
   Init();
        ^
/usr/include/znc/Template.h: In constructor ‘CTemplate::CTemplate(const CString&)’:
/usr/include/znc/Template.h:124:52: error: class ‘CTemplate’ does not have any field named ‘m_sFileName’
  CTemplate(const CString& sFileName) : MCString(), m_sFileName(sFileName), m_spOptions(new CTemplateOptions) {
                                                    ^
/usr/include/znc/Template.h:124:76: error: class ‘CTemplate’ does not have any field named ‘m_spOptions’
  CTemplate(const CString& sFileName) : MCString(), m_sFileName(sFileName), m_spOptions(new CTemplateOptions) {
                                                                            ^
/usr/include/znc/Template.h:125:8: error: ‘Init’ was not declared in this scope
   Init();
        ^
/usr/include/znc/Template.h: In constructor ‘CTemplate::CTemplate(int)’:
/usr/include/znc/Template.h:128:103: error: class ‘CTemplate’ does not have any field named ‘m_spOptions’
  CTemplate(const std::shared_ptr<CTemplateOptions>& Options, CTemplate* pParent = NULL) : MCString(), m_spOptions(Options
                                                                                                       ^
/usr/include/znc/Template.h:128:115: error: ‘Options’ was not declared in this scope
 emplate(const std::shared_ptr<CTemplateOptions>& Options, CTemplate* pParent = NULL) : MCString(), m_spOptions(Options) {
                                                                                                                ^
/usr/include/znc/Template.h:129:8: error: ‘Init’ was not declared in this scope
   Init();
        ^
/usr/include/znc/Template.h:130:3: error: ‘m_pParent’ was not declared in this scope
   m_pParent = pParent;
   ^
/usr/include/znc/Template.h:130:15: error: ‘pParent’ was not declared in this scope
   m_pParent = pParent;
               ^
/usr/include/znc/Template.h: In member function ‘void CTemplate::AddTagHandler(int)’:
/usr/include/znc/Template.h:137:3: error: ‘m_vspTagHandlers’ was not declared in this scope
   m_vspTagHandlers.push_back(spTagHandler);
   ^
/usr/include/znc/Template.h:137:30: error: ‘spTagHandler’ was not declared in this scope
   m_vspTagHandlers.push_back(spTagHandler);
                              ^
/usr/include/znc/Template.h: At global scope:
/usr/include/znc/Template.h:138:2: error: expected unqualified-id at end of input
  }
  ^
[ !! ] Error while building "push.so"
Makefile:13: recipe for target 'push.so' failed
make: *** [push.so] Error 1
```

I'm using the `znc` and `znc-dev` packages on Debian testing.

**Comment by jreese** [comment]
I can't replicate this build failure, on either Arch or Mac, after building from git using the znc-1.6.3 tag.  I don't have a Debian box to test on, but it sounds like either a problem with the ZNC packages, or something else with your local machine configuration.  Can you try building ZNC from source and see if the problem persists?

**Comment by jimmydorry** [comment]
Works for me on 1.6.3 and it's been a week since this guy shared an error, without any follow up.

I will point out that make did not work for me, but znc-buildmod (or w/e it is), worked perfectly.

**Comment by Daniel15** [comment]
> it's been a week since this guy shared an error, without any follow up.

Sorry, my week was pretty busy :stuck_out_tongue: 

> Can you try building ZNC from source and see if the problem persists?

I'll try that when I get some free time!

I guess since you can't replicate the problem, feel free to close this issue if you like.
